### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by Sokoloft** [Akascape/CTkMenuBar#10]
Hello.

Sorry this isn't an issue. However I'm unsure how I'd use this as a context menu. So if I where to right click specifically on a label. It'd open this menu with a couple of options. Specifically at the position the mouse cursor is at.

If this is possible. Hopefully you can add it to the readme as an example.

Thanks.

**Comment by Akascape** [comment]
@Sokoloft Try this example: https://www.akascape.com/coding/how-to-make-a-popup-menu-in-customtkinter
