### ISSUE TITLE
Horizontal menu spacing between 'CustomDropdownMenu' and 'add_submenu' is large

### ISSUE THREAD

**Issue by matthew-efseaff** [Akascape/CTkMenuBar#13]
The horizontal spacing between a 'CustomDropdownMenu' and an 'add_submenu' is larger than I'd like it to be. Is there a way to shrink this distance down?
Thank you

![Menu_spacing](https://github.com/Akascape/CTkMenuBar/assets/150963343/944b57f8-db81-4623-9977-3ec29c18f66a)

**Comment by Akascape** [comment]
@matthew-efseaff Try padx value in negative

**Comment by matthew-efseaff** [comment]
> @matthew-efseaff Try padx value in negative

The code below shifts the main menu left (relative to parent 'Settings', compare with original image above) but does nothing to close the gap between menu and submenu.
`self.drop_menu_settings = CustomDropdownMenu(widget=self.menu_bar_settings, padx=-15)`

![Menu_spacing2](https://github.com/Akascape/CTkMenuBar/assets/150963343/31c2e14d-9462-4132-a5eb-78d4c7a79df2)

Where else can I try? padx isn't recognized as an option anywhere else (add_submenu, add_option...)
Thank you

**Comment by Akascape** [comment]
@matthew-efseaff Is your window not scaled to 100%, maybe it's a scaling issue. You can deactivate scaling in customtkinter.

**Comment by VillainousSsnake** [comment]
> @matthew-efseaff Is your display not scaled to 100%, maybe it's a scaling issue. You can deactivate scaling in customtkinter.

How would I fix the spacing without deactivating the scaling awareness? I'm having the same problem and if I turn the scaling awareness off it makes my application look very small.

**Comment by Akascape** [comment]
@VillainousSsnake Will fix it soon

**Comment by matthew-efseaff** [comment]
Once scaling awareness is turned off (or left on) using:
`customtkinter.deactivate_automatic_dpi_awareness()`
further calls to change the scaling like below:
```
customtkinter.set_widget_scaling(float_value)  # widget dimensions and text size
customtkinter.set_window_scaling(float_value)  # window geometry dimensions
```
cause the horizontal spacing of CustomDropdownMenu and the add_submenu to behave poorly.
![75](https://github.com/Akascape/CTkMenuBar/assets/150963343/6e15c2a4-3bc7-42e7-a916-94ba004d1440)
![125](https://github.com/Akascape/CTkMenuBar/assets/150963343/b4cd42c9-6fe9-4009-b948-b58d1067927f)

**Comment by VillainousSsnake** [comment]
> @VillainousSsnake Will fix it soon

Thank you!

**Comment by Akascape** [comment]
@VillainousSsnake @matthew-efseaff Now no need to deactivate scaling, I have fixed this, update to the latest version.
