### ISSUE TITLE
Unexpected cursor behavior on win system

### ISSUE THREAD

**Issue by Rfaelv** [Akascape/CTkMenuBar#14]
As a win user, I've noticed that the cursor is always set to default mode (arrow) when hover the app's menu. And the default Tkinter menu works respecting this statament. However, in CTkMenuBar the cursor is set to pointer mode.

**Comment by Akascape** [comment]
@Rfaelv Now you can change the cursor by adding `cursor="arrow"` parameter.
For the buttons, you can configure the same after placing them.
