### ISSUE TITLE
Submenu still showing even when mouse cursor not on button

### ISSUE THREAD

**Issue by VillainousSsnake** [Akascape/CTkMenuBar#16]
# The submenu still showing even when the mouse cursor is not on the button

in this example below, only the "Export Project As" button should be showing the menu, but as you can see when move the mouse off it still shows the menu:
![problem_example](https://github.com/Akascape/CTkMenuBar/assets/144048072/a777f9f1-1f78-438d-ac86-0a1a9b672a32)

**Comment by Akascape** [comment]
Will work on these bugs tomorrow.

**Comment by Akascape** [comment]
@VillainousSsnake Fixed, update to latest version
