### ISSUE TITLE
Geometry manager error while using grid

### ISSUE THREAD

**Issue by DIY-TECH-HACKER** [Akascape/CTkMenuBar#19]
Unable to use the CTkMenuBar due to a error from geometry manager 

![image](https://github.com/Akascape/CTkMenuBar/assets/110291267/da6809e0-68dd-4974-848f-644e6a0db692)

**Comment by Akascape** [comment]
@DIY-TECH-HACKER The default geometry method is set to pack, you have to manually set the menu in grid if you are using grid method in the main window.
```python
menu = CTkMenuBar(master=self)
menu.grid()
```

**Comment by DIY-TECH-HACKER** [comment]
Thank you for your reply
