### ISSUE TITLE
Submenu Disappearing

### ISSUE THREAD

**Issue by vihaanmody1** [Akascape/CTkMenuBar#20]
Hello,

Whenever I try to hover on the submenu, it suddenly disappears in 1 second.
I also tried clicking but no luck.
Can you please fix this?

 Thank You

**Comment by Akascape** [comment]
@vihaanmody1 Which OS are you using?

**Comment by VillainousSsnake** [comment]
> @vihaanmody1 Which OS are you using? Are you using any other binding in the app?

It happens to me, and I am on windows

**Comment by VillainousSsnake** [comment]
The problem is when you hover over the dropdown for a couple of seconds, it disappears for no reason.

**Comment by vihaanmody1** [comment]
> @vihaanmody1 Which OS are you using? Are you using any other binding in the app?

I am using windows 11.

**Comment by vihaanmody1** [comment]
> The problem is when you hover over a submenu dropdown for a couple of seconds, it disappears for no reason.

Same

**Comment by vihaanmody1** [comment]
No solutions?

**Comment by Akascape** [comment]
@vihaanmody1 Can you show a screen recording? I am not able to find this bug

**Comment by vihaanmody1** [comment]
https://github.com/Akascape/CTkMenuBar/assets/105392905/f08b8829-2796-426e-92de-505496b2cb94

**Comment by Akascape** [comment]
@sagara939 @VillainousSsnake Update to v0.5
