### ISSUE TITLE
Error with "customdropdownmenu"

### ISSUE THREAD

**Issue by sagara939** [Akascape/CTkMenuBar#21]
Hi,

i have this error when use CustomDropDownMenu:

`File "C:\Python3\Lib\site-packages\CTkMenuBar\dropdown_menu.py", line 72, in __init__
    self.menu_seed_object.configure(command=self.toggleShow)
  File "C:\Python3\Lib\site-packages\CTkMenuBar\menu_bar.py", line 69, in configure
    super().configure(**kwargs)
  File "C:\Python3\Lib\site-packages\customtkinter\windows\widgets\ctk_frame.py", line 167, in configure
    super().configure(require_redraw=require_redraw, **kwargs)
  File "C:\Python3\Lib\site-packages\customtkinter\windows\widgets\core_widget_classes\ctk_base_class.py", line 133, in configure
    check_kwargs_empty(kwargs, raise_error=True)
  File "C:\Python3\Lib\site-packages\customtkinter\windows\widgets\utility\utility_functions.py", line 18, in check_kwargs_empty
    raise ValueError(f"{list(kwargs_dict.keys())} are not supported arguments. Look at the documentation for supported arguments.")
ValueError: ['command'] are not supported arguments. Look at the documentation for supported arguments.`

my code:
```
import customtkinter
from CTkMenuBar import *

app = customtkinter.CTk()

menu = CTkMenuBar(master=app)
menu.add_cascade("Menu")
menu = CustomDropdownMenu(widget=menu)
menu.add_option(option="value") 
menu.add_separator() 
submenu = menu.add_submenu("submenu") 
app.mainloop()
```

If I use "CTkTitleMenu" the app startup, but i see only "Menu" button without the customdropdownmenu (but i don't have the error above.

OS: windows 10
Python: 3.11.0 64bit

Thanks!

**Comment by sagara939** [comment]
No solutions?

**Comment by Akascape** [comment]
@sagara939 Why are you using the same 'menu' variable for both CTkMenu and customdropdown?

**Comment by sagara939** [comment]
> @sagara939 Why are you using the same 'menu' variable for both CTkMenuBar and customdropdown?

This is the last code, I'm trying all ways I think. But i have same result if I use a different variable for customdropdown.

**Comment by sagara939** [comment]
Hi @Akascape , have you any idea for help me? :)

**Comment by Akascape** [comment]
@sagara939 When you use `menu.add_cascade("Menu")`, this returns a button and you have to use this in the widget of customdropdown:
```python
import customtkinter
from CTkMenuBar import *

app = customtkinter.CTk()

menu = CTkMenuBar(master=app)
button1 = menu.add_cascade("Menu")

dmenu = CustomDropdownMenu(widget=button1)
dmenu.add_option(option="value") 
dmenu.add_separator() 
submenu = dmenu.add_submenu("submenu")

app.mainloop()

```

**Comment by Akascape** [comment]
@sagara939 @VillainousSsnake Update to v0.5

**Comment by sagara939** [comment]
> @sagara939 When you use `menu.add_cascade("Menu")`, this returns a button and you have to use this in the widget of customdropdown:
> 
> ```python
> import customtkinter
> from CTkMenuBar import *
> 
> app = customtkinter.CTk()
> 
> menu = CTkMenuBar(master=app)
> button1 = menu.add_cascade("Menu")
> 
> dmenu = CustomDropdownMenu(widget=button1)
> dmenu.add_option(option="value") 
> dmenu.add_separator() 
> submenu = dmenu.add_submenu("submenu")
> 
> app.mainloop()
> ```

Nice, thanks, it works!!
