### ISSUE TITLE
Configure error

### ISSUE THREAD

**Issue by HojdaAdelin** [Akascape/CTkMenuBar#22]
I created: 
`home_drop = CustomDropdownMenu(widget=home, padx=-5, pady=-25, bg_color="#333333", font=("", 14), corner_radius=4, separator_color="#b0b0b0",hover_color="#4d4d4d")`

and after this I wanted to change the hover_color with configure(int the same .py file:
`home_drop.configure(hover_color="red")`

but I get this error:
`Traceback (most recent call last):
  File "c:\Projects\CodeNimble\src\main.py", line 9, in <module>
    window = MainWindow()
             ^^^^^^^^^^^^
  File "c:\Projects\CodeNimble\src\GUI\gui.py", line 46, in __init__
    home_drop.configure(hover_color="red")
  File "C:\Users\""\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_frame.py", line 167, in configure
    super().configure(require_redraw=require_redraw, **kwargs)
  File "C:\Users\""\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\core_widget_classes\ctk_base_class.py", line 133, in configure
    check_kwargs_empty(kwargs, raise_error=True)
  File "C:\Users\""\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\utility\utility_functions.py", line 18, in check_kwargs_empty
    raise ValueError(f"{list(kwargs_dict.keys())} are not supported arguments. Look at the documentation for supported arguments.")
ValueError: ['hover_color'] are not supported arguments. Look at the documentation for supported arguments.`

**Comment by HojdaAdelin** [comment]
Also for "text_color"

**Comment by Akascape** [comment]
Configure method is not implemented, will add in next version.

**Comment by HojdaAdelin** [comment]
Ok. But what should I do now? Is there another option? I used configure option because I created different themes and I updated the widgets with that method.

**Comment by Akascape** [comment]
@HojdaAdelin Use this code for now:
```python
def configure_dropdown(dropdown, **kwargs):
    try:
        dropdown.configure(**kwargs)
    except ValueError:
        pass
    try:
        for widget in dropdown.winfo_children():
            widget.configure(**kwargs)
    except ValueError:
        pass

...
configure_dropdown(dropdown1, hover_color="red", text_color="white")
```

**Comment by Akascape** [comment]
@HojdaAdelin I will the .configure method soon

**Comment by Akascape** [comment]
@HojdaAdelin Added both configure and cget method, update to v0.6
