### ISSUE TITLE
#20 Issue Fixed But Very Slow and Laggy

### ISSUE THREAD

**Issue by vihaanmody1** [Akascape/CTkMenuBar#23]
Hello,

The #20 issue was fixed with the 0.5 upgrade, but I saw that it is very slow and laggy compared to the 0.4 upgrade.
Can you make it faster?

Thank you

**Comment by Akascape** [comment]
@vihaanmody1 I am not facing any lags, can you describe where you find the lag?

**Comment by vihaanmody1** [comment]
I face the lag when you hover over the submenu. Any other menus are fine.
