### ISSUE TITLE
Doesn't like switching themes

### ISSUE THREAD

**Issue by RunsOnRum** [Akascape/CTkMenuBar#24]
Hello, I am running into an issue where the menu bar (CTkTitleMenu) disappears/shows a large background box on theme switching (light/dark). It appears to behave more with my dark mode as the application would load and function properly until switching, where light theme will load with large background box (colored) and then if I switch to dark mode, the menu will disappear until I click on the title bar. These issues occur even without specifying color properties.

I have upgraded to the latest version but the issue persists. I am currently on custom tkinter 5.1.3 due to other issues I run into with the later versions (I have also updated all my packages including custom tkinter but no luck). Please let me know if you require any further information. Also, accept my thanks for all your hard work that you have contributed to the custom tkinter community!!

![image](https://github.com/Akascape/CTkMenuBar/assets/9207350/dedb71db-d413-4a95-b9d7-876aeec9ede5)

**Comment by vihaanmody1** [comment]
I faced the same issue. Only works on dark mode.

**Comment by Akascape** [comment]
@vihaanmody1 Fixed, will fix the lag issue next and release the update.

**Comment by vihaanmody1** [comment]
Thanks a lot...

**Comment by RunsOnRum** [comment]
Much appreciated @Akascape. Thank you for your time and efforts!
