### ISSUE TITLE
Postcommand function

### ISSUE THREAD

**Issue by sagara939** [Akascape/CTkMenuBar#25]
Hi! I'm here again.

It is possibile add "postcommand" for the customdropdown menu funcion? 

i need to creare a dynamic submenu, generated with a list of files in a specific directory. 

Example. 
"File" button, i press it, open the dropdown window. In this window i have all TXT file of a specific directory. With the thinker menu function i can do it with "postcommand" funciont in the menu button creation. 

How can i do it here? 

Thanks!
(sorry for my noob english)

**Comment by Akascape** [comment]
@sagara939 Added postcommand parameter, here is an example:
```python
import customtkinter
from CTkMenuBar import *

root = customtkinter.CTk()
root.geometry("600x200")

all_files = []

def add_list():
    new_files = ["A.txt", "B.txt", "C.txt", "D.txt"] # get file list
    for file in new_files:
        if file not in all_files:
            dropdown1.add_option(file)
            all_files.append(file)
            
menu = CTkMenuBar(root)
button_1 = menu.add_cascade("File", postcommand=add_list)

dropdown1 = CustomDropdownMenu(widget=button_1)

root.mainloop()
```
