### ISSUE TITLE
Unable to use cget and configure in add_option

### ISSUE THREAD

**Issue by DIY-TECH-HACKER** [Akascape/CTkMenuBar#26]
I am unable to use cget and configure in add_option and getting error 

Error 👇👇👇👇

Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\(c drive)\Python\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "D:\(c drive)\Python\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "D:\(c drive)\Python\Lib\site-packages\CTkMenuBar\dropdown_menu.py", line 90, in selectOption
    command()
  File "d:\INTELLECT 2.0\Intellect 2.0 copy.py", line 99, in Tooltip_Status
    View_Button_Dropdown_Option.cget("option")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'cget'

**Comment by Akascape** [comment]
@DIY-TECH-HACKER Please give the code to test

**Comment by DIY-TECH-HACKER** [comment]
def Tooltip_Status():
      View_Button_Dropdown_Option.cget("option")

  View_Button_Dropdown = CustomDropdownMenu(widget=View_Button)
  View_Button_Dropdown_Option = View_Button_Dropdown.add_option(option="✓ Tooltip",command=Tooltip_Status)

**Comment by Akascape** [comment]
View_Button_Dropdown_Option is defined as None when you call cget() method

**Comment by DIY-TECH-HACKER** [comment]
Is there anyway to change the text given in option after some process in the program ?

**Comment by Akascape** [comment]
@DIY-TECH-HACKER I will add this feature in next update, don't worry

**Comment by DIY-TECH-HACKER** [comment]
Thanks a lot...

**Comment by Akascape** [comment]
@DIY-TECH-HACKER Fixed, try the new version.

**Comment by DIY-TECH-HACKER** [comment]
> @DIY-TECH-HACKER Fixed, try the new version.

@Akascape Thanks a lot it is working beautifully 

Your working is a huge support to the people who are using customtkinter and please keep doing it...
