### ISSUE TITLE
Submenu disapearing

### ISSUE THREAD

**Issue by VillainousSsnake** [Akascape/CTkMenuBar#28]
The submenu disappears when you hover over the first dropdown menu's button, then hover over the sub-dropdown's buttons.

I'm on the latest Python 3.11 release, windows 11, and CTkMenuBar version 0.7.

https://github.com/Akascape/CTkMenuBar/assets/144048072/dd30536d-af57-4804-a266-944950c90e98

**Comment by VillainousSsnake** [comment]
> @VillainousSsnake Try the new version, this issue is hard to fix but I tried.

This did not fix the issue and it is still happening.

**Comment by VillainousSsnake** [comment]
This update actually may have made the issue worse @Akascape

**Comment by VillainousSsnake** [comment]
because now it isn't just happening when you hover over the buttons, it is happening when you go in-between the buttons too

**Comment by Akascape** [comment]
@VillainousSsnake I actually refered the sub menu behaviour of other applications, and I found that the menu only appears when you hover over the button for a few milliseconds, it is not just immediate.

**Comment by VillainousSsnake** [comment]
> @VillainousSsnake I actually refered the sub menu behaviour of other applications, and I found that the menu only appears when you hover over the button for a few milliseconds, it is not just immediate, and it doesn't show if the hover time is very less and if the mouse left early.
> 
> Isn't this behaviour working in the new version?

I don't understand, but the submenu is still disappearing.

**Comment by iLollek** [comment]
Hi, I currently have a PR for this open that fixes this Issue: #46
