### ISSUE TITLE
Error when creating menubar

### ISSUE THREAD

**Issue by codedreamin** [Akascape/CTkMenuBar#3]
Hi,

Thanks for another great addition to customtkinter, I'm having issues with the menubar.
I get the following error when I attempt to create a menu.

![image](https://github.com/Akascape/CTkMenuBar/assets/140753117/97a4eb1b-2e23-433b-825b-51e66874ae23)

![image](https://github.com/Akascape/CTkMenuBar/assets/140753117/6d922618-ada0-46cb-9fea-9a34192115f7)

**Comment by Akascape** [comment]
@codedreamin Refer the examples.

**Comment by codedreamin** [comment]
@Akascape 
Is there a way to not get an error message when I close the app window?

![image](https://github.com/Akascape/CTkMenuBar/assets/140753117/b72882f0-e394-42aa-89f6-a0c043a2c40f)

**Comment by Akascape** [comment]
@Akascape destroy that widget before exiting using wm_protocol.

**Comment by codedreamin** [comment]
@Akascape 
![image](https://github.com/Akascape/CTkMenuBar/assets/140753117/69027e3c-d19b-4697-87b0-7a7523e482cd)

The widget is getting destroyed before the window but the error message remains.

**Comment by Akascape** [comment]
@Akascape Also destroy the dropdown.

**Comment by codedreamin** [comment]
![image](https://github.com/Akascape/CTkMenuBar/assets/140753117/b4613a83-726f-4ddf-be87-58895257642e)

![image](https://github.com/Akascape/CTkMenuBar/assets/140753117/209d7425-58d2-4552-8069-672b819b5bd8)

I don't know what else to destroy

**Comment by Akascape** [comment]
@codedreamin Ok, don't worry, I will investigate about this issue later.

**Comment by codedreamin** [comment]
@Akascape 

No worries, thank you!

**Comment by Akascape** [comment]
@codedreamin Check the new version!
