### ISSUE TITLE
MIT or CC0 license?

### ISSUE THREAD

**Issue by limafresh** [Akascape/CTkMenuBar#37]
The repository is CC0, but I just found that __init__.py specifies MIT.

**Comment by Akascape** [comment]
@limafresh Use the code as MIT licensed.

**Comment by limafresh** [comment]
Thanks!

**Comment by limafresh** [comment]
And the question is, if I included CTkMenuBar in my project and included the CC0 file in the composition, but did not include the file with MIT, but I did not remove the mention in __init__.py, then I did not violate anything?

**Comment by Akascape** [comment]
@limafresh You are safe to use the library with a CC0 license. Don't worry about the MIT part, I will remove it. The whole project follows the CC0 license as only that file is valid for the repo.

**Comment by limafresh** [comment]
And I packed it when there was a tag about MIT in __init__.py, will I have to repack it? Or is it possible to be under CC0 even with a tag about MIT?

**Comment by Akascape** [comment]
@limafresh The whole project follows CC0. There is no license file uploaded anywhere else except the CC0.

**Comment by limafresh** [comment]
Thanks, and have a good day!
