### ISSUE TITLE
Overlapping submenus

### ISSUE THREAD

**Issue by codedreamin** [Akascape/CTkMenuBar#5]
Hi,

I currently have two submenus that are above each other (import/export). If you quickly mouse over both of them, both submenus end up appearing at the same time and overlapping. 

![image](https://github.com/Akascape/CTkMenuBar/assets/140753117/91723c85-427d-4a15-83de-bcf483c743b4)

**Comment by Akascape** [comment]
@codedreamin FIXED, update to v0.2
